#!/bin/bash

git_root_dir="$(git rev-parse --show-toplevel)"
abort_regex=(
  "^# Copyright ([0-9]{4}-)?(?!$(date '+%Y'))([0-9]{4}),.*$" \
  "Sony Corporation" \
  "xTakashi.Honda@jp.sony.com" \
)

for FILE in $(git --no-pager diff --cached --name-status | cut -c3-); do
  for ((i = 0; i < ${#abort_regex[@]}; i++)) {
    if grep -P "${abort_regex[i]}" "$git_root_dir/$FILE" 2>/dev/null; then
      echo "Matched abort_regex. Please check the file."
      echo "Regex: ${abort_regex[i]}"
      echo "File: $FILE"
      exit 1
    fi
  }
done
