#!/bin/bash

# to disable this hook: git config hooks.pre-push.disabled true
if git config hooks.pre-push.disabled >/dev/null; then
  exit 0
fi

while read local_ref local_sha1 remote_ref remote_sha1
do
  if [[ "${remote_ref##refs/heads/}" =~ "master|main" ]]; then
    echo "Do not push the branch!"
    exit 1
  fi
done
