cask_args appdir: "/Applications"

tap "caskroom/cask"
tap "sanemat/font"
tap "dart-lang/dart"

brew "dart"
brew "python3"
brew "macvim", args: ["with-override-system-vim"]
brew "direnv"
brew "fasd"
brew "ghq"
brew "git"
brew "gnu-sed", args: ["with-default-names"]
brew "jq"
brew "ricty"
brew "peco"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "zsh"
brew "reattach-to-user-namespace"
brew "mas"
cask "google-chrome"
cask "firefox"
cask "google-japanese-ime"
cask "iterm2"
cask "jitouch"
cask "dropbox"
cask "shiftit"
cask "quicksilver"
cask "1password"
cask "clipy"
cask "istat-menus"
mas "Xcode", id: 497799835
