#!/bin/bash

go get -u github.com/motemen/ghq
go get -u github.com/dinedal/textql
go get -u github.com/laurent22/massren
go get -u github.com/peco/peco/cmd/peco
go get -u github.com/pranavraja/tldr
go get -u github.com/wallix/awless
