onboarding = false
[theme]
name = "cappuccin"
auto_switch = false
[terminal]
default_shell = "/opt/homebrew/bin/fish"
[update]
[keys]
# https://herdr.dev/docs/configuration/#keybindings
prefix = "ctrl+t"
next_tab = "prefix+n"
new_workspace = "prefix+C"
previous_tab = "prefix+shift+n"
next_workspace = "prefix+ctrl+n"
previous_workspace = "prefix+ctrl+shift+n"
split_vertical = "prefix+|"

[ui]
confirm_close = true
prompt_new_tab_name = false
show_agent_labels_on_pane_borders = true
