#!/bin/bash
set -eu

install() {
  local url=https://$1.git
  local dir=${2:-~/src/$1}
  local is_git_dir=$( ( cd $dir 2> /dev/null && git rev-parse 2> /dev/null ) && echo true || echo false )

  if [ $is_git_dir = false ]; then
    git clone $url $dir
  else
    ( cd $dir; git up )
  fi

}

install github.com/tmux-plugins/tpm                       ~/.tmux/plugins/tpm
# install github.com/seebi/tmux-colors-solarized

install github.com/sstephenson/rbenv                      ~/.rbenv
install github.com/sstephenson/ruby-build                 ~/.rbenv/plugins/ruby-build
# install github.com/sstephenson/rbenv-default-gems         ~/.rbenv/plugins/rbenv-default-gems
# install github.com/amatsuda/gem-src                       ~/.rbenv/plugins/gem-src

install github.com/nodenv/nodenv                          ~/.nodenv
install github.com/nodenv/node-build                      ~/.nodenv/plugins/node-build

install github.com/syl20bnr/spacemacs                     ~/.emacs.d

# install github.com/JakeBecker/elixir-ls

# install github.com/seebi/dircolors-solarized
