#!/bin/bash

function vim_plugins {
  echo "####    vim plugins    ####"
  vim -n -e -s -S ~/.vimrc +'verbose NeoBundleUpdate' +'! echo; echo; echo NeoBundleupdatesLog' +'verbose NeoBundleUpdatesLog' +'! echo' +quit
}

function oh_my_zsh {
  echo "####    oh-my-zsh    ####"
  ZSH=~/.oh-my-zsh
  /usr/bin/env ZSH=$ZSH /bin/sh $ZSH/tools/upgrade.sh
}

function homebrew {
  echo "####    homebrew    ####"
  brew update
  echo
  echo "brew outdated"
  brew outdated
}

vim_plugins
oh_my_zsh
homebrew
