#!/bin/bash

# TODO: consider using package management tool.
#   for example: https://glide.sh/

go get -u github.com/motemen/ghq
go get -u github.com/dinedal/textql
go get -u github.com/zimbatm/direnv
go get -u github.com/laurent22/massren
go get -u github.com/peco/peco/cmd/peco
go get -u github.com/pranavraja/tldr
go get -u github.com/moul/advanced-ssh-config/cmd/assh
