#!/bin/bash
set -e

DOTFILES_DIR=$(cd $(dirname $0)/.. && pwd)

vim() {
  mkdir -p ~/.vim/{backups,swaps,undo,bundle}
  ln -sf $DOTFILES_DIR/gvimrc ~/.gvimrc
  ln -sf $DOTFILES_DIR/vimrc ~/.vimrc
  ln -sfn ~/.vim ~/.config/nvim
  ln -sf $DOTFILES_DIR/vimrc ~/.config/nvim/init.vim
  ln -sf $DOTFILES_DIR/vim/filetype.vim ~/.vim/filetype.vim
  ln -sfn $DOTFILES_DIR/vim/nerdtree_plugin ~/.vim/nerdtree_plugin
  ln -sfn $DOTFILES_DIR/vim/UltiSnips ~/.vim/UltiSnips
}

emacs() {
  ln -sf $DOTFILES_DIR/spacemacs ~/.spacemacs
}

tmux() {
  ln -sf $DOTFILES_DIR/tmux.conf ~/.tmux.conf
}

karabiner() {
  mkdir -p ~/.config/karabiner/assets
  find $DOTFILES_DIR/karabiner -type f -name '*.json' \
    -exec ln -sf {} ~/.config/karabiner/assets/complex_modifications \;
}

hammerspoon() {
  ln -sf $DOTFILES_DIR/hammerspoon/init.lua ~/.hammerspoon/init.lua
}

zsh() {
  ln -sf $DOTFILES_DIR/zshrc ~/.zshrc
  ln -sf $DOTFILES_DIR/zshenv ~/.zshenv
  ln -sfn $DOTFILES_DIR/zsh ~/.zsh
}

rest() {
  ln -sf $DOTFILES_DIR/bashrc ~/.bashrc
  ln -sf $DOTFILES_DIR/ctags ~/.ctags
  ln -sf $DOTFILES_DIR/eslintrc ~/.eslintrc
  ln -sf $DOTFILES_DIR/gitconfig ~/.gitconfig
  ln -sf $DOTFILES_DIR/gitignore ~/.gitignore
  # TODO: Linuxの場合の考慮
  ln -sf $HOMEBREW_PREFIX/share/git-core/contrib/diff-highlight/diff-highlight ~/bin/diff-highlight
  ln -sf $DOTFILES_DIR/irbrc ~/.irbrc
  ln -sf $DOTFILES_DIR/pryrc ~/.pryrc
  ln -sf $DOTFILES_DIR/rubocop.yml ~/.rubocop.yml
  ln -sf $DOTFILES_DIR/tigrc ~/.tigrc
  ln -sf $DOTFILES_DIR/tig_functions.sh ~/.tig_functions.sh
  ln -sf $DOTFILES_DIR/gemrc ~/.gemrc
  ln -sf $DOTFILES_DIR/agignore ~/.agignore

  mkdir -p ~/.lein
  ln -sf $DOTFILES_DIR/profiles.clj ~/.lein/profiles.clj

  mkdir -p ~/.rbenv
  ln -sf $DOTFILES_DIR/rbenv/default-gems ~/.rbenv/default-gems

  mkdir -p ~/.git_templates/hooks
  ls $DOTFILES_DIR/git_templates/hooks | xargs -I% ln -sf $DOTFILES_DIR/git_templates/hooks/% ~/.git_templates/hooks/%

  ln -sfn $DOTFILES_DIR/peco ~/.peco

  mkdir -p ~/bin

  touch ~/.zshrc.local
}

main() {
  if [ $# = 0 ]; then
    echo "Usage: ./link [all|APP]"
    exit
  fi

  echo "DOTFILES_DIR: $DOTFILES_DIR"
  echo "you will setup [$1]"
  echo -n "proceed?(y/n): "
  read answer
  if [[ ! $answer =~ ^y ]]; then
    echo quit
    exit
  fi

  if [ $1 = all ]; then
    vim
    emacs
    tmux
    rest
    zsh
  else
    "$1"
  fi
}

main "$@"
