#!/bin/bash
set -e

ln -sf ~/.dotfiles/bashrc ~/.bashrc
ln -sf ~/.dotfiles/ctags ~/.ctags
ln -sf ~/.dotfiles/gitconfig ~/.gitconfig
ln -sf ~/.dotfiles/gitignore ~/.gitignore
ln -sf ~/.dotfiles/gvimrc ~/.gvimrc
ln -sf ~/.dotfiles/irbrc ~/.irbrc
ln -sf ~/.dotfiles/pryrc ~/.pryrc
ln -sf ~/.dotfiles/rubocop.yml ~/.rubocop.yml
ln -sf ~/.dotfiles/tigrc ~/.tigrc
ln -sf ~/.dotfiles/tmux.conf ~/.tmux.conf
ln -sf ~/.dotfiles/vimperatorrc ~/.vimperatorrc
ln -sf ~/.dotfiles/vimrc ~/.vimrc
ln -sf ~/.dotfiles/zshrc ~/.zshrc
ln -sf ~/.dotfiles/zshrc.darwin ~/.zshrc.darwin
ln -sf ~/.dotfiles/zshrc.linux ~/.zshrc.linux
ln -sf ~/.dotfiles/gemrc ~/.gemrc

mkdir -p ~/.atom
ln -sf ~/.dotfiles/atom/config.cson ~/.atom/config.cson
ln -sf ~/.dotfiles/atom/init.coffee ~/.atom/init.coffee
ln -sf ~/.dotfiles/atom/keymap.cson ~/.atom/keymap.cson
ln -sf ~/.dotfiles/atom/snippets.cson ~/.atom/snippets.cson
ln -sf ~/.dotfiles/atom/styles.less ~/.atom/styles.less

mkdir -p ~/.rbenv
ln -sf ~/.dotfiles/rbenv/default-gems ~/.rbenv/default-gems

mkdir -p ~/.vim
ln -sf ~/.dotfiles/vim/filetype.vim ~/.vim/filetype.vim

mkdir -p ~/.git_templates/hooks
ln -sf ~/.dotfiles/git_templates/hooks/pre-commit ~/.git_templates/hooks/pre-commit
ln -sf ~/.dotfiles/git_templates/hooks/pre-push ~/.git_templates/hooks/pre-push

mkdir -p ~/.vimperator/plugin
ln -sf ~/src/github.com/vimpr/vimperator-plugins/plugin_loader.js ~/.vimperator/plugin/plugin_loader.js

ln -sf ~/src/github.com/seebi/dircolors-solarized/dircolors.256dark ~/.dircolors

mkdir -p ~/.vim/{backups,swaps,undo,bundle}

mkdir -p ~/bin

touch ~/.zshrc.local
