#!/bin/bash
set -e

continue_on_error() {
  set +e
  $@
  if ! [ $? = 0 ]; then
    echo "a command failed: $@"
    echo "continue anyway..."
  fi
  set -e
}

ln -sf ~/.dotfiles/bashrc ~/.bashrc
ln -sf ~/.dotfiles/ctags ~/.ctags
ln -sf ~/.dotfiles/eslintrc ~/.eslintrc
ln -sf ~/.dotfiles/gitconfig ~/.gitconfig
ln -sf ~/.dotfiles/gitignore ~/.gitignore
ln -sf ~/.dotfiles/gvimrc ~/.gvimrc
ln -sf ~/.dotfiles/irbrc ~/.irbrc
ln -sf ~/.dotfiles/pryrc ~/.pryrc
ln -sf ~/.dotfiles/rubocop.yml ~/.rubocop.yml
ln -sf ~/.dotfiles/tigrc ~/.tigrc
ln -sf ~/.dotfiles/tmux.conf ~/.tmux.conf
ln -sf ~/.dotfiles/vimperatorrc ~/.vimperatorrc
ln -sf ~/.dotfiles/vimrc ~/.vimrc
ln -sf ~/.dotfiles/zshrc ~/.zshrc
ln -sf ~/.dotfiles/zshrc.darwin ~/.zshrc.darwin
ln -sf ~/.dotfiles/zshrc.linux ~/.zshrc.linux
ln -sf ~/.dotfiles/gemrc ~/.gemrc

ln -sfn ~/.vim ~/.config/nvim
ln -sf ~/.vimrc ~/.config/nvim/init.vim

mkdir -p ~/.atom
ln -sf ~/.dotfiles/atom/config.cson ~/.atom/config.cson
ln -sf ~/.dotfiles/atom/init.coffee ~/.atom/init.coffee
ln -sf ~/.dotfiles/atom/keymap.cson ~/.atom/keymap.cson
ln -sf ~/.dotfiles/atom/snippets.cson ~/.atom/snippets.cson
ln -sf ~/.dotfiles/atom/styles.less ~/.atom/styles.less

mkdir -p ~/.rbenv
ln -sf ~/.dotfiles/rbenv/default-gems ~/.rbenv/default-gems

mkdir -p ~/.vim
ln -sf ~/.dotfiles/vim/filetype.vim ~/.vim/filetype.vim
ln -sfn ~/.dotfiles/vim/nerdtree_plugin ~/.vim/nerdtree_plugin
ln -sfn ~/.dotfiles/vim/UltiSnips ~/.vim/UltiSnips

mkdir -p ~/.git_templates/hooks
ls ~/.dotfiles/git_templates/hooks | xargs -I% ln -sf ~/.dotfiles/git_templates/hooks/% ~/.git_templates/hooks/%

mkdir -p ~/.vimperator/plugin
ln -sf ~/src/github.com/vimpr/vimperator-plugins/plugin_loader.js ~/.vimperator/plugin/plugin_loader.js

ln -sf ~/src/github.com/seebi/dircolors-solarized/dircolors.256dark ~/.dircolors

ln -sfn ~/.dotfiles/peco ~/.peco

mkdir -p ~/.oh-my-zsh/custom/themes
ln -sf ~/.dotfiles/oh-my-zsh/custom/themes/gallois.zsh-theme ~/.oh-my-zsh/custom/themes/gallois.zsh-theme

mkdir -p ~/.vim/{backups,swaps,undo,bundle}

# TODO: this is not working as intended
continue_on_error ln -s ~/.dotfiles/ssh ~/.ssh

mkdir -p ~/bin

touch ~/.zshrc.local
