#!/bin/bash -e

cat Brewfile.base > Brewfile
brew leaves | sed 's/^/install /' >> Brewfile
# カレントディレクトリにamethystファイルがあるためにエラーとなってしまうためのworkaround
( pushd $HOMEBREW_ROOT > /dev/null; brew cask list | sed 's/^/cask install /'; popd > /dev/null) >> Brewfile
