#!/bin/bash

# to disable this hook: git config hooks.pre-push.disabled true
if git config hooks.pre-push.disabled >/dev/null; then
  exit 0
fi

prohibited_branches="(master|develop|main)"
while read local_ref local_sha remote_ref remote_sha
do
  if [[ "$remote_ref" =~ ^.*/$prohibited_branches$ ]]; then
    cat <<-EOS
--------------------------------------------------

DO NOT PUSH TO $remote_ref DIRECTLY!

--------------------------------------------------
EOS
    exit 1
  fi
done
